//! Internal brush state during a stroke.
//! Corresponds to `states[]` array in mypaint-brush.c:93.
//! Field order MUST match the JSON `states` array in brushsettings.json.

use crate::BrushState as BrushStateEnum;

/// Internal brush state.
#[derive(Debug, Clone, Copy)]
pub struct BrushState {
    pub x: f32,
    pub y: f32,
    pub pressure: f32,
    pub partial_dabs: f32,
    pub actual_radius: f32,
    pub smudge_ra: f32,
    pub smudge_ga: f32,
    pub smudge_ba: f32,
    pub smudge_a: f32,
    pub last_getcolor_r: f32,
    pub last_getcolor_g: f32,
    pub last_getcolor_b: f32,
    pub last_getcolor_a: f32,
    pub last_getcolor_recentness: f32,
    pub actual_x: f32,
    pub actual_y: f32,
    pub norm_dx_slow: f32,
    pub norm_dy_slow: f32,
    pub norm_speed1_slow: f32,
    pub norm_speed2_slow: f32,
    pub stroke: f32,
    pub stroke_started: f32,
    pub custom_input: f32,
    pub rng_seed: f32,
    pub actual_elliptical_dab_ratio: f32,
    pub actual_elliptical_dab_angle: f32,
    pub direction_dx: f32,
    pub direction_dy: f32,
    pub declination: f32,
    pub ascension: f32,
    pub viewzoom: f32,
    pub viewrotation: f32,
    pub direction_angle_dx: f32,
    pub direction_angle_dy: f32,
    pub attack_angle: f32,
    pub flip: f32,
    pub gridmap_x: f32,
    pub gridmap_y: f32,
    pub declinationx: f32,
    pub declinationy: f32,
    pub dabs_per_basic_radius: f32,
    pub dabs_per_actual_radius: f32,
    pub dabs_per_second: f32,
    pub barrel_rotation: f32,
}

impl BrushState {
    pub fn zeroed() -> Self {
        Self {
            x: 0.0, y: 0.0, pressure: 0.0,
            partial_dabs: 0.0, actual_radius: 0.0,
            smudge_ra: 0.0, smudge_ga: 0.0, smudge_ba: 0.0, smudge_a: 0.0,
            last_getcolor_r: 0.0, last_getcolor_g: 0.0, last_getcolor_b: 0.0, last_getcolor_a: 0.0,
            last_getcolor_recentness: 0.0,
            actual_x: 0.0, actual_y: 0.0,
            norm_dx_slow: 0.0, norm_dy_slow: 0.0,
            norm_speed1_slow: 0.0, norm_speed2_slow: 0.0,
            stroke: 0.0, stroke_started: 0.0,
            custom_input: 0.0, rng_seed: 0.0,
            actual_elliptical_dab_ratio: 1.0,
            actual_elliptical_dab_angle: 90.0,
            direction_dx: 0.0, direction_dy: 0.0,
            declination: 90.0, ascension: 0.0,
            viewzoom: 1.0, viewrotation: 0.0,
            direction_angle_dx: 0.0, direction_angle_dy: 0.0,
            attack_angle: 0.0, flip: -1.0,
            gridmap_x: 0.0, gridmap_y: 0.0,
            declinationx: 0.0, declinationy: 0.0,
            dabs_per_basic_radius: 0.0,
            dabs_per_actual_radius: 0.0,
            dabs_per_second: 0.0,
            barrel_rotation: 0.0,
        }
    }

    pub fn get(&self, state: BrushStateEnum) -> f32 {
        match state {
            BrushStateEnum::X => self.x,
            BrushStateEnum::Y => self.y,
            BrushStateEnum::Pressure => self.pressure,
            BrushStateEnum::PartialDabs => self.partial_dabs,
            BrushStateEnum::ActualRadius => self.actual_radius,
            BrushStateEnum::SmudgeRa => self.smudge_ra,
            BrushStateEnum::SmudgeGa => self.smudge_ga,
            BrushStateEnum::SmudgeBa => self.smudge_ba,
            BrushStateEnum::SmudgeA => self.smudge_a,
            BrushStateEnum::LastGetcolorR => self.last_getcolor_r,
            BrushStateEnum::LastGetcolorG => self.last_getcolor_g,
            BrushStateEnum::LastGetcolorB => self.last_getcolor_b,
            BrushStateEnum::LastGetcolorA => self.last_getcolor_a,
            BrushStateEnum::LastGetcolorRecentness => self.last_getcolor_recentness,
            BrushStateEnum::ActualX => self.actual_x,
            BrushStateEnum::ActualY => self.actual_y,
            BrushStateEnum::NormDxSlow => self.norm_dx_slow,
            BrushStateEnum::NormDySlow => self.norm_dy_slow,
            BrushStateEnum::NormSpeed1Slow => self.norm_speed1_slow,
            BrushStateEnum::NormSpeed2Slow => self.norm_speed2_slow,
            BrushStateEnum::Stroke => self.stroke,
            BrushStateEnum::StrokeStarted => self.stroke_started,
            BrushStateEnum::CustomInput => self.custom_input,
            BrushStateEnum::RngSeed => self.rng_seed,
            BrushStateEnum::ActualEllipticalDabRatio => self.actual_elliptical_dab_ratio,
            BrushStateEnum::ActualEllipticalDabAngle => self.actual_elliptical_dab_angle,
            BrushStateEnum::DirectionDx => self.direction_dx,
            BrushStateEnum::DirectionDy => self.direction_dy,
            BrushStateEnum::Declination => self.declination,
            BrushStateEnum::Ascension => self.ascension,
            BrushStateEnum::Viewzoom => self.viewzoom,
            BrushStateEnum::Viewrotation => self.viewrotation,
            BrushStateEnum::DirectionAngleDx => self.direction_angle_dx,
            BrushStateEnum::DirectionAngleDy => self.direction_angle_dy,
            BrushStateEnum::AttackAngle => self.attack_angle,
            BrushStateEnum::Flip => self.flip,
            BrushStateEnum::GridmapX => self.gridmap_x,
            BrushStateEnum::GridmapY => self.gridmap_y,
            BrushStateEnum::Declinationx => self.declinationx,
            BrushStateEnum::Declinationy => self.declinationy,
            BrushStateEnum::DabsPerBasicRadius => self.dabs_per_basic_radius,
            BrushStateEnum::DabsPerActualRadius => self.dabs_per_actual_radius,
            BrushStateEnum::DabsPerSecond => self.dabs_per_second,
            BrushStateEnum::BarrelRotation => self.barrel_rotation,
        }
    }

    pub fn set(&mut self, state: BrushStateEnum, value: f32) {
        match state {
            BrushStateEnum::X => self.x = value,
            BrushStateEnum::Y => self.y = value,
            BrushStateEnum::Pressure => self.pressure = value,
            BrushStateEnum::PartialDabs => self.partial_dabs = value,
            BrushStateEnum::ActualRadius => self.actual_radius = value,
            BrushStateEnum::SmudgeRa => self.smudge_ra = value,
            BrushStateEnum::SmudgeGa => self.smudge_ga = value,
            BrushStateEnum::SmudgeBa => self.smudge_ba = value,
            BrushStateEnum::SmudgeA => self.smudge_a = value,
            BrushStateEnum::LastGetcolorR => self.last_getcolor_r = value,
            BrushStateEnum::LastGetcolorG => self.last_getcolor_g = value,
            BrushStateEnum::LastGetcolorB => self.last_getcolor_b = value,
            BrushStateEnum::LastGetcolorA => self.last_getcolor_a = value,
            BrushStateEnum::LastGetcolorRecentness => self.last_getcolor_recentness = value,
            BrushStateEnum::ActualX => self.actual_x = value,
            BrushStateEnum::ActualY => self.actual_y = value,
            BrushStateEnum::NormDxSlow => self.norm_dx_slow = value,
            BrushStateEnum::NormDySlow => self.norm_dy_slow = value,
            BrushStateEnum::NormSpeed1Slow => self.norm_speed1_slow = value,
            BrushStateEnum::NormSpeed2Slow => self.norm_speed2_slow = value,
            BrushStateEnum::Stroke => self.stroke = value,
            BrushStateEnum::StrokeStarted => self.stroke_started = value,
            BrushStateEnum::CustomInput => self.custom_input = value,
            BrushStateEnum::RngSeed => self.rng_seed = value,
            BrushStateEnum::ActualEllipticalDabRatio => self.actual_elliptical_dab_ratio = value,
            BrushStateEnum::ActualEllipticalDabAngle => self.actual_elliptical_dab_angle = value,
            BrushStateEnum::DirectionDx => self.direction_dx = value,
            BrushStateEnum::DirectionDy => self.direction_dy = value,
            BrushStateEnum::Declination => self.declination = value,
            BrushStateEnum::Ascension => self.ascension = value,
            BrushStateEnum::Viewzoom => self.viewzoom = value,
            BrushStateEnum::Viewrotation => self.viewrotation = value,
            BrushStateEnum::DirectionAngleDx => self.direction_angle_dx = value,
            BrushStateEnum::DirectionAngleDy => self.direction_angle_dy = value,
            BrushStateEnum::AttackAngle => self.attack_angle = value,
            BrushStateEnum::Flip => self.flip = value,
            BrushStateEnum::GridmapX => self.gridmap_x = value,
            BrushStateEnum::GridmapY => self.gridmap_y = value,
            BrushStateEnum::Declinationx => self.declinationx = value,
            BrushStateEnum::Declinationy => self.declinationy = value,
            BrushStateEnum::DabsPerBasicRadius => self.dabs_per_basic_radius = value,
            BrushStateEnum::DabsPerActualRadius => self.dabs_per_actual_radius = value,
            BrushStateEnum::DabsPerSecond => self.dabs_per_second = value,
            BrushStateEnum::BarrelRotation => self.barrel_rotation = value,
        }
    }
}
